stages:
  - calculate_version
  - restore
  - test
  - build
  - pack
  - publish-version
  - publish

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  NUGET_PACKAGES: "$CI_PROJECT_DIR/.nuget"
  NUGET_SOURCE: "https://gitlab.com/api/v4/groups/125542281/-/packages/nuget/index.json"

.nuget_setup: &nuget_setup
  - dotnet nuget remove source gitlab || true
  - dotnet nuget add source "$NUGET_SOURCE"
      --name gitlab
      --username "TAG_GITLAB_TOKEN"
      --password "$TAG_GITLAB_TOKEN"
      --store-password-in-clear-text

.calculate_version:
  stage: calculate_version
  image: node:20
  script:
    - git clone https://gitlab-ci-token:${TAG_GITLAB_TOKEN}@gitlab.com/company/infrastructure/cloud/test-libs-versions.git
    - cd test-libs-versions/scripts
    - npm ci
    - VERSION=$(node index.js | grep "VERSION=" | cut -d'=' -f2)
    - echo "SEMVER=$VERSION" >> $CI_PROJECT_DIR/build.env
  artifacts:
    reports:
      dotenv: build.env

.restore:
  stage: restore
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - *nuget_setup
    - dotnet restore

.build:
  stage: build
  needs:
    - job: calculate_version
      artifacts: true
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - *nuget_setup
    - dotnet restore
    - dotnet build --configuration Release --no-restore -p:Version=$SEMVER

.test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - *nuget_setup
    - dotnet test --configuration Release

.pack:
  stage: pack
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - *nuget_setup
    - dotnet restore
    - for i in $(ls src/**/*.csproj); do
        dotnet pack ./$i --configuration Release --output ./publish -p:Version=$SEMVER;
      done
  artifacts:
    paths:
      - "./publish/*.nupkg"

.publish-version:
  stage: publish-version
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - *nuget_setup
    - dotnet restore
    - dotnet publish --configuration Release --output ./publish -p:Version=$SEMVER

.publish:
  stage: publish
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet nuget push ./publish/*.nupkg
        --source "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json"
        --api-key "$TAG_GITLAB_TOKEN"
